report:
	xelatex Finalhw.tex
	bibtex Finalhw
	xelatex Finalhw.tex
	xelatex Finalhw.tex

Slide:
	xelatex Finalhw_beamer.tex
	bibtex Finalhw_beamer
	xelatex Finalhw_beamer.tex
	xelatex Finalhw_beamer.tex